openapi: 3.0.1
info:
  title: Network-API
  version: 0.0.1-SNAPSHOT
servers:
- url: /api/v1/
paths:
  /users/{userId}:
    delete:
      description: Deletes user and relationship outgoing from user
      operationId: deleteUser
      parameters:
      - description: Id of the user
        explode: false
        in: path
        name: userId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "204":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NullableEmptyObject'
          description: The user and its relationships were deleted successfully
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Internal Error
      tags:
      - User
      x-eov-operation-handler: controllers/UserController
    get:
      description: Get user info
      operationId: getUser
      parameters:
      - description: Id of the user
        explode: false
        in: path
        name: userId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetUserResponse'
          description: Get user infos
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Internal Error
      tags:
      - User
      x-eov-operation-handler: controllers/UserController
  /users/{userId}/activities:
    get:
      description: Get user activities
      operationId: getUserActivities
      parameters:
      - description: Id of the user
        explode: false
        in: path
        name: userId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetUserActivitiesResponse'
          description: Get user infos
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Internal Error
      tags:
      - User
      x-eov-operation-handler: controllers/UserController
  /users/:
    get:
      description: Get user list
      operationId: getUsers
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetUsersResponse'
          description: User list
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Internal Error
      tags:
      - User
      x-eov-operation-handler: controllers/UserController
    post:
      description: Create a new user
      operationId: createUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserRequest'
        description: Create user input
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetUserResponse'
          description: User info
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Internal Error
      tags:
      - User
      x-eov-operation-handler: controllers/UserController
  /activity/{activityId}:
    delete:
      description: delete activity and related relationships
      operationId: deleteActivity
      parameters:
      - description: Id of the activity
        explode: false
        in: path
        name: activityId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "204":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NullableEmptyObject'
          description: The activity and its relationships were deleted successfully
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Internal Error
      tags:
      - Activity
      x-eov-operation-handler: controllers/ActivityController
    get:
      description: Get activity info
      operationId: getActivity
      parameters:
      - description: Id of the activity
        explode: false
        in: path
        name: activityId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetActivityResponse'
          description: Get activity info
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Internal Error
      tags:
      - Activity
      x-eov-operation-handler: controllers/ActivityController
  /activity/{activityId}/users:
    get:
      description: Get users with relationship to activity
      operationId: getActivityUsers
      parameters:
      - description: Id of the activity
        explode: false
        in: path
        name: activityId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetActivityUsersResponse'
          description: Get activity users'
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Internal Error
      tags:
      - Activity
      x-eov-operation-handler: controllers/ActivityController
  /activity/:
    get:
      description: Get activity list
      operationId: getActivities
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetActivitiesResponse'
          description: Activity list
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Internal Error
      tags:
      - Activity
      x-eov-operation-handler: controllers/ActivityController
    post:
      description: Create a new activity
      operationId: createActivity
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateActivityRequest'
        description: Create activity
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetActivityResponse'
          description: User info
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Internal Error
      tags:
      - Activity
      x-eov-operation-handler: controllers/ActivityController
  /relationship/:
    post:
      description: Create a new relationship
      operationId: createRelationship
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateRelationshipRequest'
        description: Create relationship input
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetRelationshipResponse'
          description: User info
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Internal Error
      tags:
      - Relationship
      x-eov-operation-handler: controllers/RelationshipController
  /relationship/{relationshipId}:
    delete:
      description: Deletes relationship
      operationId: deleteRelationship
      parameters:
      - description: Id of the relationship
        explode: false
        in: path
        name: relationshipId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "204":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NullableEmptyObject'
          description: the relationship was deleted successfully
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Internal Error
      tags:
      - Relationship
      x-eov-operation-handler: controllers/RelationshipController
components:
  schemas:
    NullableEmptyObject:
      additionalProperties: false
      nullable: true
      title: Nullable empty object
      type: object
    ErrorResponse:
      additionalProperties: true
      type: object
    GetActivityUserResponse:
      additionalProperties: false
      example:
        user:
          userId: 467366a1-af34-468a-9363-480699272ee0
          name: Olivier
        relationship:
          relationshipId: 9bf1586c-eb60-43b5-8f67-2d4059e4ffa0
          type: LIKES
          userId: 467366a1-af34-468a-9363-480699272ee0
          activityId: 9bf1586c-eb60-43b5-8f67-2d4059e4ffae
      properties:
        user:
          $ref: '#/components/schemas/GetUserResponse'
        relationship:
          $ref: '#/components/schemas/GetRelationshipResponse'
      required:
      - relationship
      - user
      type: object
    GetActivityUsersResponse:
      additionalProperties: false
      example:
      - user:
          userId: 467366a1-af34-468a-9363-480699272ee0
          name: Olivier
        relationship:
          relationshipId: 9bf1586c-eb60-43b5-8f67-2d4059e4ffa0
          type: LIKES
          userId: 467366a1-af34-468a-9363-480699272ee0
          activityId: 9bf1586c-eb60-43b5-8f67-2d4059e4ffae
      - user:
          userId: 467366a1-af34-468a-9363-480699272ee1
          name: Guillaume
        relationship:
          relationshipId: 9bf1586c-eb60-43b5-8f67-2d4059e4ffb0
          type: LIKES
          userId: 467366a1-af34-468a-9363-480699272ee1
          activityId: 467366a1-af34-468a-9363-480699272ee1
      items:
        $ref: '#/components/schemas/GetActivityUserResponse'
      type: array
    GetUserActivityResponse:
      additionalProperties: false
      example:
        activity:
          activityId: 467366a1-af34-468a-9363-480699272ee0
          name: Tennis
        relationship:
          relationshipId: 9bf1586c-eb60-43b5-8f67-2d4059e4ffa0
          type: LIKES
          userId: 9bf1586c-eb60-43b5-8f67-2d4059e4ffaf
          activityId: 9bf1586c-eb60-43b5-8f67-2d4059e4ffae
      properties:
        activity:
          $ref: '#/components/schemas/GetActivityResponse'
        relationship:
          $ref: '#/components/schemas/GetRelationshipResponse'
      required:
      - activity
      - relationship
      type: object
    GetUserActivitiesResponse:
      additionalProperties: false
      example:
      - activity:
          activityId: 467366a1-af34-468a-9363-480699272ee0
          name: Tennis
        relationship:
          relationshipId: 9bf1586c-eb60-43b5-8f67-2d4059e4ffa0
          type: LIKES
          userId: 9bf1586c-eb60-43b5-8f67-2d4059e4ffaf
          activityId: 9bf1586c-eb60-43b5-8f67-2d4059e4ffae
      - activity:
          activityId: 467366a1-af34-468a-9363-480699272ee1
          name: Cooking
        relationship:
          relationshipId: 9bf1586c-eb60-43b5-8f67-2d4059e4ffb0
          type: LIKES
          userId: 9bf1586c-eb60-43b5-8f67-2d4059e4ffaf
          activityId: 467366a1-af34-468a-9363-480699272ee1
      items:
        $ref: '#/components/schemas/GetUserActivityResponse'
      type: array
    CreateUserRequest:
      additionalProperties: false
      example:
        name: Olivier
      properties:
        name:
          type: string
      required:
      - name
      type: object
    GetUserResponse:
      additionalProperties: false
      example:
        name: name
        userId: userId
      properties:
        userId:
          type: string
        name:
          type: string
      required:
      - name
      - userId
      type: object
    GetUsersResponse:
      additionalProperties: false
      example:
      - name: Guillaume
        userId: 467366a1-af34-468a-9363-480699272ee0
      - name: Olivier
        userId: 467366a1-af34-468a-9363-480699272ee1
      items:
        $ref: '#/components/schemas/GetUserResponse'
      type: array
    CreateActivityRequest:
      additionalProperties: false
      example:
        name: Cooking
      properties:
        name:
          type: string
      required:
      - name
      type: object
    GetActivityResponse:
      additionalProperties: false
      example:
        activityId: 467366a1-af34-468a-9363-480699272ee0
        name: Tennis
      properties:
        activityId:
          type: string
        name:
          type: string
      required:
      - activityId
      - name
      type: object
    GetActivitiesResponse:
      additionalProperties: false
      example:
      - name: Cooking
        activityId: 467366a1-af34-468a-9363-480699272ee0
      - name: Tennis
        activityId: 467366a1-af34-468a-9363-480699272ee1
      items:
        $ref: '#/components/schemas/GetActivityResponse'
      type: array
    CreateRelationshipRequest:
      additionalProperties: false
      example:
        type: LIKES
        userId: 60ecefee-a015-4875-b2f5-ae0641c17465
        activityId: 9bf1586c-eb60-43b5-8f67-2d4059e4ffa0
      properties:
        type:
          $ref: '#/components/schemas/RelationshipType'
        userId:
          type: string
        activityId:
          type: string
      required:
      - activityId
      - type
      - userId
      type: object
    GetRelationshipResponse:
      additionalProperties: false
      example:
        relationshipId: 9bf1586c-eb60-43b5-8f67-2d4059e4ffa0
        type: LIKES
        userId: 9bf1586c-eb60-43b5-8f67-2d4059e4ffaf
        activityId: 9bf1586c-eb60-43b5-8f67-2d4059e4ffae
      properties:
        relationshipId:
          type: string
        type:
          $ref: '#/components/schemas/RelationshipType'
        userId:
          type: string
        activityId:
          type: string
      required:
      - activityId
      - relationshipId
      - type
      - userId
      type: object
    RelationshipType:
      enum:
      - LIKES
      - HATES
      type: string
