openapi: 3.0.1

info:
  title: Network-API
  version: 0.0.1-SNAPSHOT

servers:
  - url: /api/v1/

paths:
  /users/{userId}:
    get:
      description: Get user info
      operationId: getUser
      parameters:
        - name: userId
          description: Id of the user
          required: true
          in: path
          schema:
            type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetUserResponse'
          description: Get user infos
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Internal Error
      tags:
        - User
    delete:
      description: Deletes user and relationship outgoing from user
      operationId: deleteUser
      parameters:
        - name: userId
          description: Id of the user
          required: true
          in: path
          schema:
            type: string
      responses:
        "204":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NullableEmptyObject'
          description: The user and its relationships were deleted successfully
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Internal Error
      tags:
        - User
  /users/{userId}/activities:
    get:
      description: Get user activities
      operationId: getUserActivities
      parameters:
        - name: userId
          description: Id of the user
          required: true
          in: path
          schema:
            type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetUserActivitiesResponse'
          description: Get user infos
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Internal Error
      tags:
        - User
  /users/:
    post:
      description: Create a new user
      operationId: createUser
      requestBody:
        description: Create user input
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserRequest'
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetUserResponse'
          description: User info
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Internal Error
      tags:
        - User

    get:
      description: Get user list
      operationId: getUsers
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetUsersResponse'
          description: User list
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Internal Error
      tags:
        - User

  /activity/{activityId}:
    get:
      description: Get activity info
      operationId: getActivity
      parameters:
        - name: activityId
          description: Id of the activity
          required: true
          in: path
          schema:
            type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetActivityResponse'
          description: Get activity info
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Internal Error
      tags:
        - Activity
    delete:
      description: delete activity and related relationships
      operationId: deleteActivity
      parameters:
        - name: activityId
          description: Id of the activity
          required: true
          in: path
          schema:
            type: string
      responses:
        "204":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NullableEmptyObject'
          description: The activity and its relationships were deleted successfully
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Internal Error
      tags:
        - Activity
  /activity/{activityId}/users:
    get:
      description: Get users with relationship to activity
      operationId: getActivityUsers
      parameters:
        - name: activityId
          description: Id of the activity
          required: true
          in: path
          schema:
            type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetActivityUsersResponse'
          description: Get activity users'
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Internal Error
      tags:
        - Activity
  /activity/:
    post:
      description: Create a new activity
      operationId: createActivity
      requestBody:
        description: Create activity
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateActivityRequest'
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetActivityResponse'
          description: User info
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Internal Error
      tags:
        - Activity
    get:
      description: Get activity list
      operationId: getActivities
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetActivitiesResponse'
          description: Activity list
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Internal Error
      tags:
        - Activity

  /relationship/:
    post:
      description: Create a new relationship
      operationId: createRelationship
      requestBody:
        description: Create relationship input
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateRelationshipRequest'
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetRelationshipResponse'
          description: User info
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Internal Error
      tags:
        - Relationship
  /relationship/{relationshipId}:
    delete:
      description: Deletes relationship
      operationId: deleteRelationship
      parameters:
        - name: relationshipId
          description: Id of the relationship
          required: true
          in: path
          schema:
            type: string
      responses:
        "204":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NullableEmptyObject'
          description: the relationship was deleted successfully
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Internal Error
      tags:
        - Relationship

components:
  schemas:

    NullableEmptyObject:
      title: Nullable empty object
      type: object
      additionalProperties: false
      nullable: true

    ErrorResponse:
      type: object
      additionalProperties: true

    GetActivityUserResponse:
      type: object
      additionalProperties: false
      required:
        - user
        - relationship
      properties:
        user:
          $ref: '#/components/schemas/GetUserResponse'
        relationship:
          $ref: '#/components/schemas/GetRelationshipResponse'
      example:
        user:
          userId: 467366a1-af34-468a-9363-480699272ee0
          name: Olivier
        relationship:
          relationshipId: 9bf1586c-eb60-43b5-8f67-2d4059e4ffa0
          type: LIKES
          userId: 467366a1-af34-468a-9363-480699272ee0
          activityId: 9bf1586c-eb60-43b5-8f67-2d4059e4ffae

    GetActivityUsersResponse:
      type: array
      additionalProperties: false
      items:
        $ref: '#/components/schemas/GetActivityUserResponse'
      example:
        - user:
            userId: 467366a1-af34-468a-9363-480699272ee0
            name: Olivier
          relationship:
            relationshipId: 9bf1586c-eb60-43b5-8f67-2d4059e4ffa0
            type: LIKES
            userId: 467366a1-af34-468a-9363-480699272ee0
            activityId: 9bf1586c-eb60-43b5-8f67-2d4059e4ffae
        - user:
            userId: 467366a1-af34-468a-9363-480699272ee1
            name: Guillaume
          relationship:
            relationshipId: 9bf1586c-eb60-43b5-8f67-2d4059e4ffb0
            type: LIKES
            userId: 467366a1-af34-468a-9363-480699272ee1
            activityId: 467366a1-af34-468a-9363-480699272ee1

    GetUserActivityResponse:
      type: object
      additionalProperties: false
      required:
        - activity
        - relationship
      properties:
        activity:
          $ref: '#/components/schemas/GetActivityResponse'
        relationship:
          $ref: '#/components/schemas/GetRelationshipResponse'
      example:
        activity:
          activityId: 467366a1-af34-468a-9363-480699272ee0
          name: Tennis
        relationship:
          relationshipId: 9bf1586c-eb60-43b5-8f67-2d4059e4ffa0
          type: LIKES
          userId: 9bf1586c-eb60-43b5-8f67-2d4059e4ffaf
          activityId: 9bf1586c-eb60-43b5-8f67-2d4059e4ffae

    GetUserActivitiesResponse:
      type: array
      additionalProperties: false
      items:
        $ref: '#/components/schemas/GetUserActivityResponse'
      example:
        - activity:
            activityId: 467366a1-af34-468a-9363-480699272ee0
            name: Tennis
          relationship:
            relationshipId: 9bf1586c-eb60-43b5-8f67-2d4059e4ffa0
            type: LIKES
            userId: 9bf1586c-eb60-43b5-8f67-2d4059e4ffaf
            activityId: 9bf1586c-eb60-43b5-8f67-2d4059e4ffae
        - activity:
            activityId: 467366a1-af34-468a-9363-480699272ee1
            name: Cooking
          relationship:
            relationshipId: 9bf1586c-eb60-43b5-8f67-2d4059e4ffb0
            type: LIKES
            userId: 9bf1586c-eb60-43b5-8f67-2d4059e4ffaf
            activityId: 467366a1-af34-468a-9363-480699272ee1


    CreateUserRequest:
      type: object
      additionalProperties: false
      required:
        - name
      properties:
        name:
          type: string
      example:
        name: Olivier

    GetUserResponse:
      type: object
      additionalProperties: false
      required:
        - userId
        - name
      properties:
        userId:
          type: string
        name:
          type: string

    GetUsersResponse:
      type: array
      additionalProperties: false
      items:
        $ref: '#/components/schemas/GetUserResponse'
      example:
        - name: Guillaume
          userId: 467366a1-af34-468a-9363-480699272ee0
        - name: Olivier
          userId: 467366a1-af34-468a-9363-480699272ee1


    CreateActivityRequest:
      type: object
      additionalProperties: false
      required:
        - name
      properties:
        name:
          type: string
      example:
        name: Cooking

    GetActivityResponse:
      type: object
      additionalProperties: false
      required:
        - activityId
        - name
      properties:
        activityId:
          type: string
        name:
          type: string
      example:
        activityId: 467366a1-af34-468a-9363-480699272ee0
        name: Tennis



    GetActivitiesResponse:
      type: array
      additionalProperties: false
      items:
        $ref: '#/components/schemas/GetActivityResponse'
      example:
        - name: Cooking
          activityId: 467366a1-af34-468a-9363-480699272ee0
        - name: Tennis
          activityId: 467366a1-af34-468a-9363-480699272ee1

    CreateRelationshipRequest:
      type: object
      additionalProperties: false
      required:
        - type
        - userId
        - activityId
      properties:
        type:
          $ref: '#/components/schemas/RelationshipType'
        userId:
          type: string
        activityId:
          type: string
      example:
        type: LIKES
        userId: 60ecefee-a015-4875-b2f5-ae0641c17465
        activityId: 9bf1586c-eb60-43b5-8f67-2d4059e4ffa0

    GetRelationshipResponse:
      type: object
      additionalProperties: false
      required:
        - relationshipId
        - type
        - userId
        - activityId
      properties:
        relationshipId:
          type: string
        type:
          $ref: '#/components/schemas/RelationshipType'
        userId:
          type: string
        activityId:
          type: string
      example:
        relationshipId: 9bf1586c-eb60-43b5-8f67-2d4059e4ffa0
        type: LIKES
        userId: 9bf1586c-eb60-43b5-8f67-2d4059e4ffaf
        activityId: 9bf1586c-eb60-43b5-8f67-2d4059e4ffae

    RelationshipType:
      type: string
      enum:
        - LIKES
        - HATES




